name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Install node modules and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: Install modules and test
        run: |
          yarn policies set-version 1.19.1
          yarn
          yarn test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_REGISTRY_TOKEN }}

