name: Release

on:
  push:
    branches: npm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Install github-release-notes and generate changelog
      run: |
        npx github-release-notes@0.17.1 changelog --generate --override --token=${{ secrets.GITHUB_TOKEN }} --changelog-filename=TEMP_CHANGELOG.md -B
      env:
        CI: true
    - name: Create and publish release
      uses: ncipollo/release-action@v1
      with:
        tag: v0.2.14-0
        bodyFile: 'TEMP_CHANGELOG.md'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://npm.pkg.github.com'
    - name: Set npm token
      uses: filipstefansson/set-npm-token-action@v1
      with:
        token: ${{ secrets.NPM_REGISTRY_TOKEN }}
    - name: Publish to npm
      run: |
        yarn policies set-version 1.19.1
        yarn
        npm publish
